version: '3'

services:
  web-help:
    image: node:lts
    working_dir: /app
    container_name: web-help
    ports:
      - 8081:8081
    volumes:
      - .:/app
    command: /bin/bash -c 'npm install; npm run start:docker'
