version: '3'

services:
  web-help:
    image: node:lts
    working_dir: /app
    container_name: web-help
    volumes:
      - .:/app
    command: /bin/bash -c 'npm install; npm run start:docker'
  proxy:
    image: nginx
    ports:
#      - 443:443
      - 8088:80
    volumes:
      - ./.docker/ingress/default.conf:/etc/nginx/conf.d/default.conf
#      - ./docker/ingress/proxy_headers.include:/etc/nginx/include.d/proxy_headers.include
    container_name: proxy
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - web-help
